"use strict";
exports.__esModule = true;
var fake_items_repository_1 = require("./communication/fake-items-repository");
var repository = new fake_items_repository_1.FakeItemsRepository();
var items = repository.getItems();
console.log('Items:');
console.log(items);
repository.deleteItem(1);
items = repository.getItems();
console.log('Delete:');
console.log(items);
repository.createItem({ name: "Monitor", price: 200 });
items = repository.getItems();
console.log('Create:');
console.log(items);
var updatedItem = repository.updateItem({ name: "PlayStation", price: 800, id: 3 });
console.log('Update:');
console.log(updatedItem);
var item = repository.getItemById(3);
console.log('Get Item By Id:');
console.log(item);
